import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  errorText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 16,
  },
  backBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#003f2f',
    borderRadius: 8,
  },
  backBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  headerBackBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
  },
  statusBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  section: {
    backgroundColor: '#fff',
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 16,
  },
  progressBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    position: 'relative',
  },
  progressStep: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
  },
  progressLine: {
    position: 'absolute',
    top: 20,
    left: '55%',
    right: '-55%',
    height: 2,
    backgroundColor: '#e0e0e0',
    zIndex: 0,
  },
  progressLineCompleted: {
    backgroundColor: '#003f2f',
  },
  progressCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    marginBottom: 6,
  },
  progressCircleCompleted: {
    backgroundColor: '#003f2f',
  },
  progressCircleActive: {
    backgroundColor: '#003f2f',
  },
  progressCircleInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
  },
  progressLabel: {
    fontSize: 11,
    color: '#aaa',
    textAlign: 'center',
  },
  progressLabelActive: {
    color: '#003f2f',
    fontWeight: '700',
  },
  progressLabelCompleted: {
    color: '#003f2f',
  },
  deliverySteps: {
    gap: 4,
  },
  deliveryStep: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    gap: 12,
  },
  deliveryStepActive: {
    backgroundColor: '#f0f4f0',
  },
  deliveryStepIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryStepIconActive: {
    backgroundColor: '#003f2f',
  },
  deliveryStepIconCompleted: {
    backgroundColor: '#e8f5e9',
    borderWidth: 1.5,
    borderColor: '#003f2f',
  },
  deliveryStepContent: {
    flex: 1,
  },
  deliveryStepLabel: {
    fontSize: 14,
    color: '#aaa',
    fontWeight: '500',
  },
  deliveryStepLabelActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },
  deliveryStepLabelCompleted: {
    color: '#003f2f',
    fontWeight: '600',
  },
  deliveryStepSubtitle: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  deliveryStepTime: {
    fontSize: 11,
    color: '#aaa',
  },
  addressLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addressText: {
    fontSize: 13,
    color: '#666',
    flex: 1,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: '#fca5a5',
    borderRadius: 10,
    backgroundColor: '#fff5f5',
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ef4444',
  },
  divider: {
    height: 1,
    backgroundColor: '#f0f0f0',
    marginTop: 8,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  productThumb: {
    width: 56,
    height: 56,
    borderRadius: 8,
  },
  productThumbPlaceholder: {
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productInfo: {
    flex: 1,
    gap: 4,
  },
  productName: {
    fontSize: 14,
    color: '#1a1a1a',
    fontWeight: '500',
  },
  productQty: {
    fontSize: 12,
    color: '#888',
  },
  productPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#666',
  },
  summaryValue: {
    fontSize: 14,
    color: '#1a1a1a',
    fontWeight: '600',
  },
  orderDateText: {
    fontSize: 12,
    color: '#aaa',
    marginTop: 16,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 36,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#666',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  reasonsList: {
    maxHeight: 280,
    paddingHorizontal: 20,
  },
  reasonItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  reasonItemSelected: {
    backgroundColor: '#f0f7f5',
    marginHorizontal: -20,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  reasonRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reasonRadioSelected: {
    borderColor: '#003f2f',
  },
  reasonRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#003f2f',
  },
  reasonText: {
    fontSize: 14,
    color: '#444',
    flex: 1,
  },
  reasonTextSelected: {
    color: '#003f2f',
    fontWeight: '600',
  },
  cancelErrorBox: {
    marginHorizontal: 20,
    marginTop: 12,
    backgroundColor: '#fee2e2',
    borderRadius: 8,
    padding: 12,
  },
  cancelErrorText: {
    fontSize: 13,
    color: '#991b1b',
    textAlign: 'center',
  },
  confirmCancelBtn: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: '#ef4444',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  confirmCancelBtnDisabled: {
    backgroundColor: '#fca5a5',
  },
  confirmCancelBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  arrivedSection: {
    backgroundColor: '#fff',
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  cancelledBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#fee2e2',
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  cancelledBannerTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#991b1b',
    marginBottom: 4,
  },
  cancelledBannerText: {
    fontSize: 13,
    color: '#991b1b',
    lineHeight: 20,
  },
  arrivedBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#e0f2fe',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  arrivedBannerText: {
    flex: 1,
    fontSize: 13,
    color: '#0369a1',
    lineHeight: 20,
    fontWeight: '500',
  },
  payBalanceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#003f2f',
  },
  payBalanceBtnDisabled: {
    opacity: 0.6,
  },
  payBalanceBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  paymentErrorBox: {
    backgroundColor: '#fee2e2',
    borderRadius: 8,
    padding: 12,
  },
  paymentErrorText: {
    fontSize: 13,
    color: '#991b1b',
    textAlign: 'center',
  },
  arrivedCancelWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#fef3c7',
    borderRadius: 10,
    padding: 14,
    marginHorizontal: 20,
    marginTop: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  arrivedCancelWarningText: {
    flex: 1,
    fontSize: 13,
    color: '#92400e',
    lineHeight: 20,
    fontWeight: '500',
  },
  attachmentBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  attachmentBtnText: {
    fontSize: 13,
    color: '#666',
  },
  contactBtnsRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  contactBtn: {
    flex: 1,
    minWidth: 140,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: '#003f2f',
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  contactBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#003f2f',
  },
});
