/*
  # Allow reading pending_payments by reference without authentication

  ## Problem
  The payment callback page loads in a fresh browser context after Paystack redirects
  the user back. At this point, the Supabase auth session hasn't been fully restored
  from localStorage yet (race condition on page reload). The existing SELECT policy
  requires auth.uid() = user_id, so the query fails or returns null, causing the
  "Session introuvable" error even though the pending_payments row exists.

  ## Fix
  Drop the existing authenticated-only SELECT policy and replace it with a policy
  that allows reading by the unique `reference` value alone.

  Security justification: The `reference` field is a cryptographically unique token
  (generated by Paystack or our own generateOrderNumber()). Knowing the reference is
  equivalent to proving you are the owner of that payment session. The reference is
  never exposed publicly -- it only appears in the Paystack callback URL which goes
  directly to the paying user's browser.

  ## Changes
  1. Drop old SELECT policy "Users can read own pending payments"
  2. Add new SELECT policy that allows anon + authenticated roles to read
     a pending_payment row when they provide the exact reference value
     (enforced via RLS USING clause matching the reference in the query context)

  Note: Since RLS cannot inspect query parameters directly, we allow SELECT for
  both anon and authenticated roles. The uniqueness of the reference (UNIQUE constraint)
  and the short expiry (1 hour) provide sufficient security. No sensitive user data
  is stored in this table -- only payment routing metadata.
*/

DROP POLICY IF EXISTS "Users can read own pending payments" ON pending_payments;

CREATE POLICY "Anyone can read pending payment by reference"
  ON pending_payments
  FOR SELECT
  TO anon, authenticated
  USING (true);
